### ISSUE TITLE
Featured Entries are showing on top no matter what page we navigate to

### ISSUE THREAD

**Issue by rafaehlers** [gravityview/Featured-Entries#15]
Featured entries should only show on the first page of the results:

## Page 1
![gv-page-1](https://user-images.githubusercontent.com/1222472/41257074-f8bce71e-6da1-11e8-9fa3-a39a00633b57.jpg)

## Page 2
![gv-page-2](https://user-images.githubusercontent.com/1222472/41257076-f9c98dce-6da1-11e8-9d7c-6050df11de6e.jpg)

Tested on GV 2.0.10 and Featured Entries 2.0.1

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/991397300387786/991520086383385)

**Comment by rafaehlers** [comment]
https://secure.helpscout.net/conversation/596151057/15317?folderId=408730

**Comment by rafaehlers** [comment]
https://secure.helpscout.net/conversation/758363737/18666/

**Comment by soulseekah** [comment]
This is intentional as far as I remember. Move entries on top will always keep them at the top, regardless of how many there are. Although the behavior is a bit weird on next pages.

Either way, I'd like to rewrite it using GF_Query instead and we can have some flexible settings.

1. Highlight featured entries (boolean)
2. Keep featured entries at the top or sort by featured first

We can combine with #2 

Also related: #16, #24

**Comment by soulseekah** [comment]
Rafael, please test and let me know how you like this. I'll add the `sticky` feature in just a bit.

**Comment by rafaehlers** [comment]
@soulseekah it still shows the featured entries on every page

**Comment by soulseekah** [comment]
I've tested this and I don't get it on every page.

![image](https://user-images.githubusercontent.com/685880/64462600-af737100-d109-11e9-9848-27ca2bdd1134.png)

![image](https://user-images.githubusercontent.com/685880/64462612-b7cbac00-d109-11e9-9d2b-707a5977e0e2.png)

Page two does not have sticky results. Can you please reverify, or send me access to a View where this is happening. Make sure you're using the develop branch.
